// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: board.sql

package database

import (
	"context"
)

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (data)
VALUES ($1)
RETURNING id
`

func (q *Queries) CreateBoard(ctx context.Context, data string) (int32, error) {
	row := q.db.QueryRowContext(ctx, createBoard, data)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getBoard = `-- name: GetBoard :one
SELECT id, data FROM boards
WHERE id = $1
`

func (q *Queries) GetBoard(ctx context.Context, id int32) (Board, error) {
	row := q.db.QueryRowContext(ctx, getBoard, id)
	var i Board
	err := row.Scan(&i.ID, &i.Data)
	return i, err
}
